// Regenerates src/icons/*.tsx and src/index.ts from the repo-root icon source
// (driven by scripts/icons.js, which reads the LESS codepoint map + src/svgs/).
// Run via `npm run codegen` (or `npm run build`) in this package.

import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync, rmSync, mkdirSync } from "node:fs";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const { loadIcons } = require(resolve(repoRoot, "scripts/icons.js"));

const pascal = (s) =>
  s.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const componentName = (name) => `Icon${pascal(name)}`;

const icons = loadIcons();
const iconsDir = resolve(here, "../src/icons");
rmSync(iconsDir, { recursive: true, force: true });
mkdirSync(iconsDir, { recursive: true });

const banner = "// Generated by scripts/codegen.mjs — do not edit.\n";

for (const { name, d } of icons) {
  const cn = componentName(name);
  writeFileSync(
    resolve(iconsDir, `${cn}.tsx`),
    `${banner}import { createIcon } from "../createIcon";\n\n` +
      `export const ${cn} = createIcon(${JSON.stringify(cn)}, ${JSON.stringify(d)});\n`
  );
}

const indexLines = [
  banner.trimEnd(),
  'export { createIcon } from "./createIcon";',
  'export type { Icon, IconProps } from "./createIcon";',
  ...icons.map(({ name }) => {
    const cn = componentName(name);
    return `export { ${cn} } from "./icons/${cn}";`;
  }),
  "",
];
writeFileSync(resolve(here, "../src/index.ts"), indexLines.join("\n"));

console.log(`@simple-line-icons/react: generated ${icons.length} components`);
